USE [master]
GO

/****** Object:  Database [FastFood]    Script Date: 10/4/2020 6:55:12 PM ******/
CREATE DATABASE [FastFood]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FastFood', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FastFood.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FastFood_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FastFood_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FastFood].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FastFood] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FastFood] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FastFood] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FastFood] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FastFood] SET ARITHABORT OFF 
GO

ALTER DATABASE [FastFood] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FastFood] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FastFood] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FastFood] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FastFood] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FastFood] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FastFood] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FastFood] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FastFood] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FastFood] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FastFood] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FastFood] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FastFood] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FastFood] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FastFood] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FastFood] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FastFood] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FastFood] SET RECOVERY FULL 
GO

ALTER DATABASE [FastFood] SET  MULTI_USER 
GO

ALTER DATABASE [FastFood] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FastFood] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FastFood] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FastFood] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FastFood] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FastFood] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FastFood] SET  READ_WRITE 
GO

